const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('powerTools', {
  getAppInfo: () => ipcRenderer.invoke('app:getInfo'),
  getLiveMetrics: () => ipcRenderer.invoke('system:getLiveMetrics'),
  enableCpuSensor: () => ipcRenderer.invoke('sensor:enable'),
  getCpuSensorStatus: () => ipcRenderer.invoke('sensor:status'),
  getStaticInfo: (force = false) => ipcRenderer.invoke('system:getStaticInfo', force),
  getSecurityInfo: (force = false) => ipcRenderer.invoke('security:getInfo', force),
  getModelCenter: (force = false, customEndpoint = '') => ipcRenderer.invoke('models:getCenter', force, customEndpoint),
  modelChat: (payload) => ipcRenderer.invoke('models:chat', payload),
  routeModel: (payload) => ipcRenderer.invoke('models:route', payload),
  getAISystemContext: (payload = {}) => ipcRenderer.invoke('models:systemContext', payload),
  getModelCredentials: () => ipcRenderer.invoke('models:credentials'),
  saveModelCredential: (provider, key) => ipcRenderer.invoke('models:saveCredential', provider, key),
  removeModelCredential: (provider) => ipcRenderer.invoke('models:removeCredential', provider),
  getFeatureLab: (force = false) => ipcRenderer.invoke('featurelab:get', force),
  getFeatureLabAdmin: () => ipcRenderer.invoke('featurelab:getAdmin'),
  applyFeatureLabAction: (featureId, action) => ipcRenderer.invoke('featurelab:apply', featureId, action),
  openFeatureLabItem: (featureId) => ipcRenderer.invoke('featurelab:open', featureId),
  copySecuritySummary: () => ipcRenderer.invoke('security:copySummary'),
  listStartupItems: (force = false) => ipcRenderer.invoke('startup:list', force),
  getProcesses: (force = false) => ipcRenderer.invoke('apps:processes', force),
  endProcess: (pid) => ipcRenderer.invoke('apps:endProcess', pid),
  restartProcess: (pid) => ipcRenderer.invoke('apps:restartProcess', pid),
  revealProcess: (pid) => ipcRenderer.invoke('apps:revealProcess', pid),
  copyProcessPath: (pid) => ipcRenderer.invoke('apps:copyProcessPath', pid),
  getInstalledApps: (force = false) => ipcRenderer.invoke('apps:installed', force),
  revealInstalledApp: (index) => ipcRenderer.invoke('apps:revealInstalled', index),
  openInstalledAppsSettings: () => ipcRenderer.invoke('apps:openInstalledSettings'),
  getNetworkOverview: (force = false) => ipcRenderer.invoke('network:getOverview', force),
  networkPing: (target) => ipcRenderer.invoke('network:ping', target),
  networkDnsLookup: (target) => ipcRenderer.invoke('network:dnsLookup', target),
  networkConnectivityTest: () => ipcRenderer.invoke('network:connectivityTest'),
  networkFlushDns: () => ipcRenderer.invoke('network:flushDns'),
  networkRenewDhcp: () => ipcRenderer.invoke('network:renewDhcp'),
  networkCopyIpConfig: () => ipcRenderer.invoke('network:copyIpConfig'),
  getVpnCenter: (force = false) => ipcRenderer.invoke('vpn:getCenter', force),
  vpnProviderAction: (provider, action) => ipcRenderer.invoke('vpn:providerAction', provider, action),
  getNetworkDiagnosticsHistory: () => ipcRenderer.invoke('network:diagnosticsHistory'),
  getIpGeolocationStatus: () => ipcRenderer.invoke('network:ipGeoStatus'),
  saveIpGeolocationKey: (key) => ipcRenderer.invoke('network:saveIpGeoKey', key),
  removeIpGeolocationKey: () => ipcRenderer.invoke('network:removeIpGeoKey'),
  lookupIpGeolocation: (ip = '') => ipcRenderer.invoke('network:ipGeoLookup', ip),
  openGeoIpify: () => ipcRenderer.invoke('network:openGeoIpify'),
  privacyDnsInspect: (domain) => ipcRenderer.invoke('privacy:dnsInspect', domain),
  privacyInspectFile: () => ipcRenderer.invoke('privacy:inspectFile'),
  privacyOpenProfile: (platform, username) => ipcRenderer.invoke('privacy:openProfile', platform, username),
  privacyOpenResource: (resource) => ipcRenderer.invoke('privacy:openResource', resource),
  privacyGetAppTrustInventory: (force = false) => ipcRenderer.invoke('privacy:appTrustInventory', force),
  privacySelectAppTrustFile: () => ipcRenderer.invoke('privacy:appTrustSelect'),
  privacyInspectInstalledApp: (index) => ipcRenderer.invoke('privacy:appTrustInstalled', index),
  privacyGetAppProtectionStatus: () => ipcRenderer.invoke('privacy:appProtectionStatus'),
  privacyOpenHashReputation: (hash) => ipcRenderer.invoke('privacy:openHashReputation', hash),
  getUpdateReleaseState: () => ipcRenderer.invoke('updates:getState'),
  checkForAppUpdates: (force = false) => ipcRenderer.invoke('updates:check', force),
  saveUpdateReleaseSettings: (payload = {}) => ipcRenderer.invoke('updates:saveSettings', payload),
  stageAndVerifyUpdate: (packageKind = 'installer') => ipcRenderer.invoke('updates:stageVerify', packageKind),
  clearUpdateStaging: () => ipcRenderer.invoke('updates:clearStaging'),
  openUpdateRelease: (url) => ipcRenderer.invoke('updates:openRelease', url),
  onUpdateReleaseProgress: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('updates:progress', handler);
    return () => ipcRenderer.removeListener('updates:progress', handler);
  },
  getGitHubStatus: () => ipcRenderer.invoke('github:status'),
  saveGitHubToken: (token) => ipcRenderer.invoke('github:saveToken', token),
  removeGitHubToken: () => ipcRenderer.invoke('github:removeToken'),
  getGitHubCenter: (force = false) => ipcRenderer.invoke('github:getCenter', force),
  getGitHubRepoDetails: (repo) => ipcRenderer.invoke('github:getRepoDetails', repo),
  selectGitHubSource: (kind = 'files') => ipcRenderer.invoke('github:selectSource', kind),
  clearGitHubSource: () => ipcRenderer.invoke('github:clearSource'),
  commitGitHubSource: (payload) => ipcRenderer.invoke('github:commitSource', payload),
  selectGitHubReleaseAssets: () => ipcRenderer.invoke('github:selectAssets'),
  clearGitHubReleaseAssets: () => ipcRenderer.invoke('github:clearAssets'),
  generateGitHubReleaseNotes: (payload) => ipcRenderer.invoke('github:generateReleaseNotes', payload),
  publishGitHubRelease: (payload) => ipcRenderer.invoke('github:publishRelease', payload),
  openGitHubLink: (url) => ipcRenderer.invoke('github:openLink', url),
  openGitHubTokenSettings: () => ipcRenderer.invoke('github:openTokenSettings'),
  getChangeJournal: () => ipcRenderer.invoke('journal:getState'),
  undoChangeJournalEntry: (id) => ipcRenderer.invoke('journal:undo', id),
  clearChangeJournal: () => ipcRenderer.invoke('journal:clear'),
  getReliabilityStatus: () => ipcRenderer.invoke('reliability:getStatus'),
  getStableReleaseStatus: () => ipcRenderer.invoke('stable:getStatus'),
  copyStableReleaseSummary: () => ipcRenderer.invoke('stable:copySummary'),
  rendererReady: () => ipcRenderer.invoke('reliability:rendererReady'),
  reportRendererError: (payload) => ipcRenderer.invoke('reliability:rendererError', payload),
  copyReliabilitySummary: () => ipcRenderer.invoke('reliability:copySummary'),
  openReliabilityLogs: () => ipcRenderer.invoke('reliability:openLogs'),
  clearReliabilityDiagnostics: () => ipcRenderer.invoke('reliability:clearDiagnostics'),
  resetHardwareCache: () => ipcRenderer.invoke('reliability:resetStaticCache'),
  getAutomationState: () => ipcRenderer.invoke('automation:getState'),
  saveAutomationRule: (rule) => ipcRenderer.invoke('automation:saveRule', rule),
  setAutomationRuleEnabled: (id, enabled) => ipcRenderer.invoke('automation:setRuleEnabled', id, enabled),
  deleteAutomationRule: (id) => ipcRenderer.invoke('automation:deleteRule', id),
  runAutomationRuleNow: (id) => ipcRenderer.invoke('automation:runRuleNow', id),
  setAutomationMasterEnabled: (enabled) => ipcRenderer.invoke('automation:setMasterEnabled', enabled),
  clearAutomationHistory: () => ipcRenderer.invoke('automation:clearHistory'),
  onAutomationEvent: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on('automation:event', handler);
    return () => ipcRenderer.removeListener('automation:event', handler);
  },
  onAutomationNavigate: (callback) => {
    const handler = (_event, view) => callback(view);
    ipcRenderer.on('automation:navigate', handler);
    return () => ipcRenderer.removeListener('automation:navigate', handler);
  },
  getPerformanceProfiles: () => ipcRenderer.invoke('performance:getProfiles'),
  getStorageInventory: (force = false) => ipcRenderer.invoke('storage:getInventory', force),
  analyzeUserFolders: () => ipcRenderer.invoke('storage:analyzeUserFolders'),
  cancelStorageAnalysis: () => ipcRenderer.invoke('storage:cancelAnalysis'),
  previewStorageCleanup: (force = false) => ipcRenderer.invoke('storage:cleanupPreview', force),
  runStorageCleanup: (categoryIds) => ipcRenderer.invoke('storage:cleanupRun', categoryIds),
  openStorageFolder: (kind) => ipcRenderer.invoke('storage:openFolder', kind),
  openStorageDrive: (letter) => ipcRenderer.invoke('storage:openDrive', letter),
  revealLargeFile: (index) => ipcRenderer.invoke('storage:revealLargeFile', index),
  setPerformanceProfile: (id) => ipcRenderer.invoke('performance:setProfile', id),
  listActivity: () => ipcRenderer.invoke('activity:list'),
  addActivity: (title, detail) => ipcRenderer.invoke('activity:add', title, detail),
  exportReport: () => ipcRenderer.invoke('report:export'),
  openSystem: (target) => ipcRenderer.invoke('system:open', target),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close')
});
